// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdemrlfqddkkjqiutxfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkZW1ybGZxZGRra2pxaXV0eGZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1Mzg3OTQsImV4cCI6MjA3MDExNDc5NH0.UkJyGEWONqLb4khjetV6SGbNEzJwxCvwyhCTfHb4X5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});